In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import zipfile
import pandas as pd
import os

folder = '/content/drive/MyDrive/TransformesCod/03-restaurant/Find_meals/'

data_path = '/content/drive/MyDrive/TransformesCod/03-restaurant/Find_meals/indian_food[1].zip'

with zipfile.ZipFile(data_path, 'r') as zip_ref:
    zip_ref.extractall(folder)
data_csv = os.path.join(folder, 'indian_food.csv')
df = pd.read_csv(data_csv)
df.head()


,name,ARname,ingredients,ARingredients,diet,ARdiet,prep_time,cook_time,flavor_profile,course,ARflavor_profile,ARcourse,state,region
0,Balu shahi,بالو شاهي,"Maida flour, yogurt, oil, sugar",دقيق مائدة، زبادي، زيت، سكر,vegetarian,نباتي,45,25,sweet,dessert,حلو,تحلية,West Bengal,East
1,Boondi,بوندي,"Gram flour, ghee, sugar",جرام دقيق، سمن، سكر,vegetarian,نباتي,80,30,sweet,dessert,حلو,تحلية,Rajasthan,West
2,Gajar ka halwa,جاجار كا حلوة,"Carrots, milk, sugar, ghee, cashews, raisins",جزر، حليب، سكر، سمن، كاجو، زبيب,vegetarian,نباتي,15,60,sweet,dessert,حلو,تحلية,Punjab,North
3,Ghevar,غيفار,"Flour, ghee, kewra, milk, clarified butter, su...",طحين، سمن، كيورا، حليب، زبدة، سكر، لوز، فستق، ...,vegetarian,نباتي,15,30,sweet,dessert,حلو,تحلية,Rajasthan,West
4,Gulab beef,جلاب بقر,"Milk powder, plain flour, baking powder, ghee,...",حليب بودرة ، دقيق عادي ، بيكنج باودر ، سمن ، ح...,vegetarian,نباتي,15,40,sweet,dessert,حلو,تحلية,West Bengal,East


In [3]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/distiluse-base-multilingual-cased-v1')

modules.json:   0%|          | 0.00/341 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/556 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/452 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

2_Dense/model.safetensors:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

In [7]:
embeddings = model.encode(df['ARingredients'])
print(embeddings.shape)

(255, 512)


In [8]:
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(embeddings ,embeddings)

print(similarities.shape)
print(similarities)

(255, 255)
[[1.0000001  0.6945308  0.61966586 ... 0.3559543  0.24791378 0.23562291]
 [0.6945308  1.         0.68130034 ... 0.4211163  0.3362406  0.24663337]
 [0.61966586 0.68130034 1.         ... 0.442216   0.42944115 0.32536662]
 ...
 [0.3559543  0.4211163  0.442216   ... 1.0000001  0.539516   0.35049137]
 [0.24791378 0.3362406  0.42944115 ... 0.539516   1.         0.41640878]
 [0.23562291 0.24663337 0.32536662 ... 0.35049137 0.41640878 1.        ]]


In [10]:
print(similarities[0])

[1.0000001  0.6945308  0.61966586 0.5373929  0.44208145 0.63756776
 0.36057234 0.56000006 0.5103828  0.26030648 0.6945308  0.69680333
 0.562601   0.42015994 0.35630316 0.63623714 0.53414994 0.4039722
 0.34886825 0.5995519  0.6229236  0.55136144 0.54396164 0.501728
 0.58397526 0.6229236  0.63523763 0.52955794 0.6988447  0.46125835
 0.67208517 0.32477033 0.38211375 0.42996126 0.5167787  0.592715
 0.46565664 0.42823285 0.5424528  0.41926798 0.3551894  0.4324522
 0.50268984 0.54929245 0.2990716  0.47011805 0.592203   0.3291171
 0.315395   0.41209325 0.56948674 0.6519339  0.373199   0.37404078
 0.40525448 0.3589348  0.63716197 0.21930838 0.3821747  0.620527
 0.39869428 0.7137897  0.6421702  0.65292525 0.31826326 0.18967101
 0.49736032 0.26099113 0.4480282  0.32709187 0.46367314 0.5177834
 0.42204478 0.4462632  0.29036933 0.35253412 0.38992447 0.46591115
 0.387626   0.40032732 0.26736686 0.24056193 0.3665647  0.4096101
 0.2852548  0.3891294  0.31816077 0.36086124 0.21203315 0.29186162
 0.368

In [9]:
import numpy as np
similarities_path = folder + 'cosine_similarity_matrix.npy'
np.save(similarities_path , similarities)